power <- read.csv("~/R working/household_power_consumption.txt", sep=";",stringsAsFactors = FALSE)
power$Date <- as.Date(power$Date,format = "%d/%m/%Y")
graphdata <- power[power$Date >= as.Date("2007/2/1") & power$Date <= as.Date("2007/2/2"),]
graphdata$Global_active_power <- as.numeric(graphdata$Global_active_power)
graphdata$datetime <- as.POSIXct(paste(graphdata$Date, graphdata$Time, sep=" "),format="%Y-%m-%d %H:%M:%S")
png(filename="~/R working/plot4.png",width=480,height=480)
par(mfrow=c(2,2))
plot(graphdata$datetime,graphdata$Global_active_power,type="l",xlab="", ylab="Global Active Power")
plot(graphdata$datetime,graphdata$Voltage,type="l",xlab="datetime", ylab="Voltage")
plot(graphdata$datetime,graphdata$Sub_metering_1,type="l",xlab="", ylab="Energy sub metering")
lines(graphdata$datetime,graphdata$Sub_metering_2,col="red")
lines(graphdata$datetime,graphdata$Sub_metering_3,col="blue")
legend('topright', c('Sub_metering_1','Sub_metering_2','Sub_metering_3'), lty=1,col=c('black', 'red', 'blue'),bty='n')
plot(graphdata$datetime,graphdata$Global_reactive_power,type="l",xlab="datetime", ylab="Global_Reactive_Power")
dev.off()
